# Generated by Django 4.2.2 on 2023-06-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_myuser_delete_courses'),
        ('project', '0002_category_comment_donation_image_projects_rating_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.myuser'),
        ),
    ]
