# Generated by Django 4.2.2 on 2023-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_repor_count_projects_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.TextField(),
        ),
    ]
