# Generated by Django 4.2.2 on 2023-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_projects_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='report_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_state',
            field=models.IntegerField(),
        ),
    ]
