# Generated by Django 4.2.2 on 2023-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_projects_report_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='report_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
