# Generated by Django 4.2.2 on 2023-06-10 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(db_column='email', max_length=75, validators=[django.core.validators.RegexValidator('[^@]+@[^@]+\\.[^@]+', 'Enter a valid email.')])),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^01[0125][0-9]{8}$', 'Enter a valid Egyption phone number.')])),
                ('image', models.CharField()),
                ('birth_date', models.DateField()),
                ('facebook_profile', models.CharField()),
                ('country', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
