# Generated by Django 4.2.2 on 2023-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_myuser_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(upload_to='static/profile_pictures'),
        ),
    ]
