# Generated by Django 4.2.2 on 2023-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(default='1990-12-12'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(default='Egypt'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='facebook_profile',
            field=models.CharField(default='https://www.facebook.com'),
        ),
    ]
